export const PRODUCTS = [
  {
    name: "Premium Laptop",
    description: "High-performance laptop for professionals",
    image: "💻",
    price: 1299,
    category: "electronics",
    featured: true,
  },
  {
    name: "Smartphone Pro",
    description: "Latest flagship smartphone",
    image: "📱",
    price: 899,
    category: "electronics",
    featured: true,
  },
  {
    name: "Wireless Headphones",
    description: "Noise-cancelling headphones",
    image: "🎧",
    price: 249,
    category: "electronics",
    featured: false,
  },
  {
    name: "Smart Watch Ultra",
    description: "Fitness tracking smartwatch",
    image: "⌚",
    price: 399,
    category: "electronics",
    featured: true,
  },
  {
    name: "Tablet Device Pro",
    description: "Portable tablet for work and play",
    image: "📱",
    price: 649,
    category: "electronics",
    featured: false,
  },
  {
    name: "Digital Camera",
    description: "Professional DSLR camera",
    image: "📷",
    price: 1499,
    category: "electronics",
    featured: true,
  },
];
